# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up the JDK
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          server-id: github
          cache: 'maven'
      - name: Configure Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          echo "::remove-matcher owner=java::"

      - name: Get Trino version
        id: trino_tag
        run: |
          trino_tag=$(./mvnw -B help:evaluate -Dexpression=dep.trino.version -q -DforceStdout)
          echo "trino_tag=$trino_tag" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
        with:
          repository: trinodb/trino
          path: trino
          ref: ${{ steps.trino_tag.outputs.trino_tag }}
      - name: Build Trino
        run: cd trino && ./mvnw -B install -DskipTests -Dair.check.skip-all -Dskip.npm -pl ':trino-main,:trino-testing,:trino-memory,:trino-tpch' -am

      - name: Build with Maven
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: ./mvnw -B package

      - name: Annotate run
        uses: trinodb/github-actions/action-surefire-report@b63800bedfbc7ab1ff2e5fe7eaecf5ab82ce6a70
        if: always()
        with:
          fail_if_no_tests: false
          skip_publishing: true
