name: Release with Maven

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'
      - name: Configure Problem Matchers
        run: |
          echo "::add-matcher::.github/problem-matcher.json"
          echo "::remove-matcher owner=java::"
      - name: Configure Git user
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Trino version
        id: trino_tag
        run: |
          trino_tag=$(./mvnw -B help:evaluate -Dexpression=dep.trino.version -q -DforceStdout)
          echo "trino_tag=$trino_tag" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
        with:
          repository: trinodb/trino
          path: trino
          ref: ${{ steps.trino_tag.outputs.trino_tag }}
      - name: Build Trino
        run: cd trino && ./mvnw -B install -DskipTests -Dair.check.skip-all -Dskip.npm -pl ':trino-main,:trino-testing,:trino-memory,:trino-tpch' -am

      - name: Prepare release
        run: ./mvnw -B release:prepare
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Build and push Docker image
        run: |
          ./docker-build.sh

      - name: Save version number in env
        run: |
          echo "VERSION=$(grep 'project.rel.pl.net.was\\:trino-cloud=' release.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Publish JAR
        run: ./mvnw -B release:perform -Darguments="-Dgpg.skip -Dmaven.deploy.skip=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ env.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          setup-java: false

      - name: Annotate run
        uses: trinodb/github-actions/action-surefire-report@b63800bedfbc7ab1ff2e5fe7eaecf5ab82ce6a70
        if: always()
        with:
          fail_if_no_tests: false
          skip_publishing: true
